language: cpp
dist: trusty

addons:
    apt:
        sources:
            # Ubuntu testing
            - ubuntu-toolchain-r-test
        packages:
            # C++17
            - g++-7
            # gdb
            - gdb
            # ninja
            - ninja-build
            # realpath
            - realpath
            # boost
            - libboost-all-dev

cache:
    ccache: true

matrix:
    compiler:
        - CC=clang CXX=clang++
        - CC=gcc   CXX=g++
    types:
        - BUILD_TYPE=Debug   CXX_FLAGS_DEBUG=-fsanitize=undefined         CXX_LFLAGS_DEBUG=-fsanitize=undefined         RUNNER=$GDB
        - BUILD_TYPE=Debug   CXX_FLAGS_DEBUG=-fsanitize=undefined,address CXX_LFLAGS_DEBUG=-fsanitize=undefined,address
        - BUILD_TYPE=Release

before_install:
    # gcc 7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    # clang 5
    - sudo add-apt-repository -y ppa:jonathonf/llvm
    # ld
    - sudo add-apt-repository -y ppa:jonathonf/binutils
    # python
    - sudo add-apt-repository -y ppa:jonathonf/python-2.7
    - sudo add-apt-repository -y ppa:jonathonf/python-3.6
    # Qt 5.9
    - sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-trusty
    # protobuf
    - git clone -b v1.10.x --single-branch --recursive https://github.com/grpc/grpc
    # Update sources
    - sudo apt-get update

install:
    # clang
    - sudo apt-get install clang-5.0
    # ld
    - sudo apt-get install binutils
    # python
    - sudo apt-get install python2.7
    - sudo apt-get install python3.6
    # Qt 5.9
    - sudo apt-get install qt510base
    # ccache
    - which clang++
    - sudo ln -s $(which ccache) /usr/lib/ccache/clang++
    - which clang++
    - which g++
    # protobuf
    - cd grpc && mkdir build && cd build
    - cmake .. -G Ninja
    - sudo ninja install -j4
    - sudo cp grpc_* /usr/local/bin
    - sudo cp *.a /usr/local/lib
    - cd ../..
    - export GRPC_LIBS=$(sh print_libs.sh)
    - echo $GRPC_LIBS

before_script:
    # Display
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Qt 5.9
    - source /opt/qt510/bin/qt510-env.sh
    - export QT_FATAL_WARNINGS=1
    # Sanitizer settings
    - export UBSAN_OPTIONS=print_stacktrace=1
    - export LSAN_OPTIONS=suppressions=../lsan.supp #ignore Qt's memory leaks
    # print versions
    - g++ --version
    - clang++ --version
    - protoc --version
    - cmake --version
    - ninja --version
    - python --version
    - python2 --version
    - python3 --version
    - gdb --version
    - ld --version
    - /usr/bin/x86_64-linux-gnu-ld --version
    # gdb flags
    - export GDB='gdb -q --return-child-result -ex "set confirm off" -ex "set pagination off" -ex "handle SIG40 nostop" -ex run -ex bt -ex quit --args'

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja ..
    - ninja -j4
    - $RUNNER ./SCE test

after_script:
    # ccache stats
    - ccache -s
