language: cpp
dist: trusty

addons:
    apt:
        sources:
            # Ubuntu testing
            - ubuntu-toolchain-r-test
        packages:
            # C++17
            - g++-7
            # ninja
            - ninja-build
            # ssl
            - libssl-dev
            # boost
            - libboost-all-dev

before_install:
    # gcc 7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    # ld
    - sudo add-apt-repository -y ppa:jonathonf/binutils
    # Qt 5.9
    - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
    # protobuf
    - git clone -b v1.10.x --single-branch --recursive https://github.com/grpc/grpc
    # Update sources
    - sudo apt-get update

install:
    # ld
    - sudo apt-get install binutils
    # Qt 5.9
    - sudo apt-get install qt59base
    # protobuf
    - cd grpc
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - sudo ninja install -j4
    - sudo cp grpc_cpp_plugin /usr/local/bin
    - sudo cp *.a /usr/local/lib
    - sudo cp *.so /usr/local/lib
    - cd ../..

before_script:
    # Display
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Qt 5.9
    - source /opt/qt59/bin/qt59-env.sh
    - export QT_FATAL_WARNINGS=1
    # ignore Qt's memory leaks
    - export LSAN_OPTIONS=suppressions=../lsan.supp
    # print versions
    - g++ --version
    - protoc --version
    - cmake --version
    - ninja --version
    - ld --version
    - /usr/bin/x86_64-linux-gnu-ld --version
    # set up build directories
    - mkdir debug_build
    - mkdir release_build

script:
    - cd debug_build
    - cmake -DCMAKE_BUILD_TYPE=DEBUG -G Ninja ..
    - ninja -j4
    - ./SCE test
    # using libfinder to find some missing symbols
    - sudo apt-get install locate
    - sudo updatedb
    - git clone https://github.com/Toeger/LibFinder
    - cd LibFinder
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - ninja -j4
    - ./libfinder -u
    - ./libfinder -s ares_inet_ntop
    - ./libfinder -s init_openssl
    - ./libfinder -s BIO_pending
    #- false #just so this test doesn't count as a successful build
    #- cd ../release_build
    #- cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja ..
    #- ninja -j4
    #- ./SCE test
