language: cpp
dist: trusty

addons:
    apt:
        sources:
            # Ubuntu testing
            - ubuntu-toolchain-r-test
        packages:
            # C++17
            - g++-7
            # ninja
            - ninja-build

before_install:
    # gcc 7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    # ld
    - sudo add-apt-repository -y ppa:jonathonf/binutils-2.30
    # Qt 5.9
    - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
    # protobuf
    - git clone -b v1.10.x --single-branch --recursive https://github.com/grpc/grpc
    # Update sources
    - sudo apt-get update

install:
    # ld
    - sudo apt-get install binutils
    # Qt 5.9
    - sudo apt-get install qt59base
    # protobuf
    - cd grpc
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - sudo ninja install -j4
    - sudo cp grpc_cpp_plugin /usr/bin
    - sudo cp *.a /usr/lib
    - sudo cp *.so /usr/lib
    - cd ../..

before_script:
    # Display
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    #- sleep 3 # wait for xvfb to start #waiting should not be necessary, compiling C++ will take care of that
    # Qt 5.9
    - source /opt/qt59/bin/qt59-env.sh
    - export QT_FATAL_WARNINGS=1
    # ignore Qt's memory leaks
    - export LSAN_OPTIONS=suppressions=../lsan.supp
    # print versions
    - g++ --version
    - protoc --version
    - cmake --version
    - ninja --version
    - ld --version
    # set up build directories
    - mkdir debug_build
    - mkdir release_build

script:
    - cd debug_build
    - cmake -DCMAKE_BUILD_TYPE=DEBUG -G Ninja ..
    - ninja -v
    #- ./SCE test
    #- cd ../release_build
    #- cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja ..
    #- ninja -j4
    #- ./SCE test
