language: cpp
dist: trusty

# C++17
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - binutils-2.26

before_install:
    # Qt 5.9
    - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
    # Protobuf 3+
    - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
    # Update sources
    - sudo apt-get update

install:
    # Qt 5.9
    - sudo apt-get install qt59base
    # Protobuf 3+
    - sudo apt-get install protobuf-compiler libprotobuf-dev

before_script:
    # Display
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # wait for xvfb to start
    # Qt 5.9
    - source /opt/qt59/bin/qt59-env.sh
    - export QT_FATAL_WARNINGS=1
    # gcc 7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    # ld
    - sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld-2.26 90
    # ignore Qt's memory leaks
    - export LSAN_OPTIONS=suppressions=lsan.supp
    # print versions
    - g++ --version
    - protoc --version

script:
    - cmake .
    - make -j
    - ./SCE test
