language: cpp
dist: trusty

# C++17
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7

before_install:
  # Qt 5.9
  - sudo add-apt-repository -y ppa:beineri/opt-qt59-trusty
  - sudo apt-get update -qq

install:
  # C++17
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Qt 5.9
  - sudo apt-get install -qq qt59base
  - source /opt/qt59/bin/qt59-env.sh

before_script:
  # Display
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - qmake
  - make -j8 release
  - make clean
  - make -j8 debug
  - ./SCE test
